#!/usr/bin/env python
""" 
    For more info on the documentation go to https://www.decawave.com/sites/default/files/dwm1001-api-guide.pdf
"""

import os
import sys
import time
import serial

class controller:
    """
        TODO Docstring
    """

    def __init__(self) :
        """
        Initialize the node, open serial port
        """
        
        # Serial port settings
        self.serialPortDWM1001_1 = serial.Serial(
            port = '/dev/ttyACM0',
            baudrate = 115200,
            timeout = 0.1,
            parity = serial.PARITY_ODD,
            stopbits = serial.STOPBITS_TWO,
            bytesize = serial.SEVENBITS
        )
        
    def main(self) :
        """
        Initialize port and dwm1001 api
        :param:
        :returns: none
        """

        # Close the serial port in case the previous run didn't closed it properly
        self.serialPortDWM1001_1.close()
        
        # Sleep for one sec
        time.sleep(1)
        
        # Open serial port
        self.serialPortDWM1001_1.open()

        # Check if the serial port is opened
        if(self.serialPortDWM1001_1.isOpen()):
            print("Port `Node1` opened: {}".format(self.serialPortDWM1001_1.name) )
        else:
            print("Can't open port `Node1`: {}".format(self.serialPortDWM1001_1.name))

        try: 
            while (True):
                self.serialPortDWM1001_1.write("s".encode())
                # Read everythin from the serial port 
                for _ in range(1): 
                    serialReadLine = self.serialPortDWM1001_1.read_until()
                    print(serialReadLine)
                    
        finally:
            print("Quitting, and sending reset command to dev board")
            self.serialPortDWM1001_1.close()
            

if __name__ == '__main__':
    
    node1 = controller()
    node1.main()
